### ISSUE TITLE
jQuery dependency, really?

### ISSUE THREAD

**Issue by imlinus** [e-oj/Magic-Grid#1]
Great lib!

However, I don't wanna add jQuery as a dependency just to add your library.

Do you have a plan to remove third-parties?
Or would you accept a pull-request if I removed it?

Cheers

**Comment by e-oj** [comment]
I plan on doing that in the future but I'll accept a pr

**Comment by jordyvandomselaar** [comment]
When you get this fixed I'll see if I can create a React version 🎉

**Comment by imlinus** [comment]
I have now created a PR :-)

**Comment by imlinus** [comment]
@jordyvandomselaar Sounds great!
I'll port it for Vue.js (since that's where I need the lib originally)
And then you create a React port and this lib should be up and running in no-time!

Cheers guys,
Gotta love open sauce <3

**Comment by imlinus** [comment]
Nice one mate!
I'm closing this issue.

Cheers
