### ISSUE TITLE
[enhancement/suggestion] this binding & destroy method

### ISSUE THREAD

**Issue by renatodeleao** [e-oj/Magic-Grid#24]
I'm late to the party but congrats for this beautiful piece of code and for your detailed explanation on CodeBurst. It's not easy to "empty ourselves" and have *a beginner's mind* when writing so 👏.

I've noticed that you're not binding `this` to your public methods. This can have unexpected results when, for example passing a public method reference to a button listener (`this` becomes the button).

```js
const mg = new MagicGrid({});
// error
someButton.addEventListener('click', mg.positionItems)

// works, but no reference, can't remove this listener after
someButton.addEventListener('click', () => mg.positionItems())

// works, but boilerplate
let mgPosItems = mg.positionItems();
someButton.addEventListener('click', mgPosItems)
``` 
- Here's a a [fiddle forked from your original example](https://jsfiddle.net/fzmy8drn/13/)

#### `.destroy()`

Another use-case that popped into my mind was a destroy method.
I have given a try at implementing [this and the above suggestions](https://github.com/renatodeleao/Magic-Grid/pull/1), so let me know if you interested in a PR.

Keep up the good work :)
Cheers

**Comment by e-oj** [comment]
Thanks for contributing! Open a PR on the dev branch and I'll accept it. 👍👍

**Comment by renatodeleao** [comment]
No prob @e-oj take a look at #26, and let me know if any updates required.

**Comment by e-oj** [comment]
Looks good. Reopen the PR on the [dev branch](https://github.com/e-oj/Magic-Grid/tree/dev).
