### ISSUE TITLE
CDN url is giving an 520 error

### ISSUE THREAD

**Issue by Dunicotech** [e-oj/Magic-Grid#58]
When loading in the magic grid via CDN I get a 520 error. The links shows this https://unpkg.com/magic-grid/dist/magic-grid.min.js. Both the minimised and normal version give the same error. Please help.

**Comment by frenicohansen** [comment]
try to use another cdn such as jsDelivr https://cdn.jsdelivr.net/npm/magic-grid/dist/magic-grid.min.js

**Comment by e-oj** [comment]
This should be working now as well
