### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by Yuliasik** [e-oj/Magic-Grid#59]
Hello @e-oj, I really like your solution for the grid position
Unfortunately, a faced an issue with the implementation of your solution. 

Could you please, support me with that?
Thanks in advance!

![image](https://user-images.githubusercontent.com/70966703/205328882-6feb4785-feb8-4efb-aedb-f118c76b6bee.png)

Here is my typescript code:
```   
 this.taskService.getTasks().subscribe(
      response => {
        this.allTasks = response
        this.dates = Array.from(this.allTasks.keys()).sort();

        const magicGrid = new MagicGrid({
          container: '.tasks',
          items: 20,
          animate: true,
          gutter: 20,
          static: false
        });
        magicGrid.listen();
        magicGrid.positionItems();
      }
    )
```

My HTML code
``` 
<div class="tasks">
  <ng-container *ngIf="allTasks && allTasks.size > 0">
    <div *ngFor="let key of dates">
      {{key}}
    </div>
  </ng-container>
</div>
```

**Comment by e-oj** [comment]
The code is running before the container has rendered. I haven't used angular in years but what ever the `useEffect` equivalent is, should fix this (I think it's `ngOnInit`). Basically you need to initialize the grid right after the component is available in the DOM.
