### ISSUE TITLE
No default export in 3.3.4 release

### ISSUE THREAD

**Issue by iainbeeston** [e-oj/Magic-Grid#76]
I've tried to upgrade to the 3.3.4 release on npm but I'm seeing this error:

    No matching export in "node_modules/magic-grid/dist/magic-grid.min.js" for import "default"

when I import magic grid into my code:

    import MagicGrid from "magic-grid"

I'm not sure what could have caused this difference between the previous release (3.2.4) and 3.3.4, but it looks like there were a lot of build tool changes?

**Comment by e-oj** [comment]
We're working on this. Should be fixed today

**Comment by e-oj** [comment]
This has been fixed in v3.3.6
